//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public System.Guid Id { get; set; }
        public string GizNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid FamilyId { get; set; }
        public string FirstNameA { get; set; }
        public string FirstNameE { get; set; }
        public string FathertNameA { get; set; }
        public string FathertNameE { get; set; }
        public string GranFathertNameA { get; set; }
        public string GrandFathertNameE { get; set; }
        public string FamilyNameA { get; set; }
        public string FamilyNameE { get; set; }
        public string MotherNameA { get; set; }
        public string MotherNameE { get; set; }
        public int Skill { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public bool MaritialStatus { get; set; }
        public bool Gender { get; set; }
        public System.Guid HousingId { get; set; }
        public System.Guid HomeTownId { get; set; }
        public System.Guid PaymentId { get; set; }
        public int Status { get; set; }
    
        public virtual FamilyId FamilyId1 { get; set; }
        public virtual HomeTown HomeTown { get; set; }
        public virtual Housing Housing { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual PersonId PersonId1 { get; set; }
    }
}
