//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid PartnerId { get; set; }
        public System.Guid SubPartnerId { get; set; }
        public string Site { get; set; }
        public string Supervisor { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Partner Partner1 { get; set; }
    }
}
