//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CurrentSupervisor { get; set; }
        public System.Guid PartnerId { get; set; }
    }
}
