//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string PartnerId { get; set; }
        public System.Guid CurrentSite { get; set; }
        public int Status { get; set; }
    }
}
