//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvyResult
    {
        public System.Guid Id { get; set; }
        public System.Guid SurvyId { get; set; }
        public System.Guid BeneficiaryId { get; set; }
        public int QuestionNumber { get; set; }
        public int AnswerNumber { get; set; }
    }
}
