//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegistation
    {
        public string GizNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string FirstNameA { get; set; }
        public string FirstNameE { get; set; }
        public string FathertNameA { get; set; }
        public string FathertNameE { get; set; }
        public string GranFathertNameA { get; set; }
        public string GrandFathertNameE { get; set; }
        public string FamilyNameA { get; set; }
        public string FamilyNameE { get; set; }
        public string MotherNameA { get; set; }
        public string MotherNameE { get; set; }
        public int Skill { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public bool MaritialStatus { get; set; }
        public bool Gender { get; set; }
        public System.Guid HousingId { get; set; }
        public System.Guid HomeTownId { get; set; }
        public System.Guid PaymentId { get; set; }
        public System.Guid Expr1 { get; set; }
        public decimal Income { get; set; }
        public int IncomeCurrency { get; set; }
        public int MembersCount { get; set; }
        public int RegularIncomeMembersCount { get; set; }
        public System.Guid Expr2 { get; set; }
        public string Number { get; set; }
        public int TypeId { get; set; }
        public int Status { get; set; }
        public int Expr3 { get; set; }
        public int Type { get; set; }
        public bool IsPersonId { get; set; }
        public bool IsFamilyId { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public string ShortDescriptionA { get; set; }
        public string ShortDescriptionE { get; set; }
        public string DescriptionA { get; set; }
        public string DescriptionE { get; set; }
        public System.Guid Expr4 { get; set; }
        public string Expr5 { get; set; }
        public int Expr6 { get; set; }
        public int Expr7 { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Expr8 { get; set; }
        public int Parent { get; set; }
    }
}
